### ISSUE TITLE
Custom sections

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/peculiarpointer#2]
Can we make a custom sections to give them some information?

Where can I find cursors?
Our mission is to make WordPress weird so we've created a gallery of cursors for you to use here:
https://weirdpress.club/pointers

In the media placeholder maybe let's say. 

Upload an image or pick one from your media library. 
The recommended image size is 64x64px and the max is 128x128px.

**Comment by Mamaduka** [comment]
Something like this?

![Screenshot-3evtf](https://user-images.githubusercontent.com/240569/75163966-87201300-5739-11ea-9859-1c25c70c9fd9.jpg)

**Comment by nickhamze** [comment]
Yeah that works.
